import pyautogui
import time
# sentence="A girl, in the Vacococha tribe of Peru, to prepare her for marriage at the age of 12, is placed in a basket in the hut of her prospective in-laws and must remain suspended over an open fire night and day for 3 months. The Spanish Inquisition once condemned the entire Netherlands to Inquisition once condmned the entire Netherlands to death for heresy. During the eighteenth century, books that were considered offensive were sometimes punished by being whipped."
# sentence="In England, the Speaker of the House is not allowed to speak. If a statue in the park of a person on a horse has both front legs in the air, the person died in battle; if the horse has one front leg in the air, the person died as a result of wounds received in battle; if the horse has all four legs on the ground, the person died of natrual causes. Peanuts are one of the ingredients of dynamite."
# sentence="In the Middle Ages, the highest court in France ordered the execution of a cow for injuring a human. A girl, in the Vacococha tribe of Peru, to prepare her for marriage at the age of 12, is placed in a basket in the hut of her prospective in-laws and must remain suspended over an open fire night and day for 3 months. The Spanish Inquisition once condemned the entire Netherlands to death for heresy,."
# sentence="You can pick your friends. you can pick your nose, but you can't pick your friend's nose. Babies are born without knee caps. They don't appear until the child reaches 2-6 years of age. Modern records do not compare with that of St Simeon the younger called stylites a monk spent the final 45 years of his life living at the top of a stone pillar on the hill of wonders near Antioch in Syria!"
# sentence="The Guinness Book of Records holds the record for being the book most often stolen from public libraries. If you removed the stomach, the spleen, 75% of the liver, 80% of the intestines, one kidney, one lung, and virtually every organ from the pelvic and groin area, the human body would still be able to survive. In 10 minutes, a hurricane releases more energy than all of the world's nuclear weapons combined."
# sentence="Ancient Greeks wove marjoram into funeral wreaths and put them on the graves of loved ones. The wreaths served as prayers for the happiness of the deceased in a future life. Breaking of a glass is traditional in some wedding ceremonies. This custom symbolizes different things. To some it is the destruction of the temple in Jerusalem, and for some it represents the fragility of a relationship.""
# sentence="Dentists have recommended that a toothbrush be kept at least 6 feet away from a toilet to avoid airborne particles resulting from the flush. The plastic things on the end of shoelaces are called aglets. Richard Millhouse the letters from the word 'criminal'. The second was William Jefferson Clinton. A crocodile can't stick its tongue out,."

# sentence="On average, 100 people choke to death on ballpoint pens every year. Thirty-give percent of the people who use personal ads for dating are already married. The Main Library at Indiana University sinks over an inch every year because when it was built, engineers failed to take into account the weight of all the books that would occupyt the building. The electric chair was invented by a dentist,."

# sentence="Human skulls had been used as drinking cups for hundreds of years. The muscles and flesh were scraped away, the bottom was hacked off and then they were suitable to hold any beverage. The first Bowie knife was forged at Washington, Arkansas. All the dirt from the foundation to build the World Trade Center in NYC was dumped into the Hudson River to form the community now known as Battery City Park."
# sentence="When Thomas Jefferson became U.S. President in 1801, 20 percent of all people in the young nation were slaves. Early Egypatians wore sandals made from woven papyrus leaves. The Marquis de Lafayette, America's Revolutionary War ally, named his only son George Washington Lafayette. Karl Marx and Friedrich Engels, the fathers of communism, wrote 500 articles for the ""New York Tribune"" from 1851 to 1862"
# sentence="Abe Silverstein, who headed NASA's Space Flight Development Program, proposed the name Apollo for the space exploration programs in the 1960's. He chose that legendary Greek name because the virile Apollo was a god who rode through the skies in a magnificent golden chariot. The precedent of naming manned spacecraft for mythological gods had been set earlier with Project Mercury, also named by Silverstein,."
# sentence="""In 1974 there were 90 tornadoes in the U.S. in one day. Satirist Jonathan Swift suggested in his essay "A Modest Proposal" that the children of the poor be sold as food to to feed the rich. This shocking essay is one of the best examples of satire you'll find. Akhbar the Great Mughal routed the Hindus under Hemu by turning their elephants against them at the battle of Panipat in the Hindu revolt,."""
# sentence="""It is legal in North Dakota to shoot an Indian on horseback, provided you are in a covered wagon. The mummified hand of a notary public, chopped off for falsely certifying a document, as a warning to other notaries for 400 years. The curtain or veil used by some Hindus and Moslems to seclude or hide their women from strangers is called a "purdah",."""

# sentence="""The first aerial photograph was taken from a balloon during the U.S. civil war. Olive oil was used for washing the body in the ancient Mediterranean world. In 1801, 20 percent of the people in the U.S. were slaves. Slaves under the last emperors of China wore pigtails so they could be picked out quickly. Dinner guests during the medieval times in England were expected to bring their own knives to the table,."""
# sentence="""after know show on both eye get right on begin well such of do fact can number help must do from form same those up child right those last possible"""
# sentence="Abe Silverstein, who headed NASA's Space Flight Development Program, proposed the name Ap"
# sentence="""Venus is the only planet that rotates clockwise. Charlie Chaplin once won third prize in a Charlie Chaplin look-alike contest. And old law in Bellingham, Washington, made it illegal for a woman to take more than three steps backwards while dancing! The glue on Israeli postage is certified kosher. The Guinness Book of Records holds the record for being the book most often stolen from public libraries."""
sentence="""The first aerial photograph was taken from a balloon during the U.S. civil war. Olive oil was used for washing the body in the ancient Mediterranean world. In 1801, 20 percent of the people in the U.S. were slaves. Slaves under the last emperors of China wore pigtails so they could be picked out quickly. Dinner guests during the medieval times in England were expected to bring their own knives to the table."""
length=len(sentence)
c=0
print ('get ready...')
time.sleep(3)
delay_between_keys = 0.06
pyautogui.write(sentence, interval=delay_between_keys)

# while c<length:
#     pyautogui.press(sentence[c])
#     c += 1 
